import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/store/AuthContext";
import { queryClient } from "@/lib/queryClient";
import { QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "react-hot-toast";
import Navbar from "@/components/Navigation/Navbar";
import Footer from "@/components/footer/footer";
import CartContextProvider from "@/store/CartContext";
import { AuthModalProvider } from "@/store/AuthModalContext";

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dosis.variable} antialiased`}>
        <QueryClientProvider client={queryClient}>
          <AuthModalProvider>
            <AuthProvider>
              <CartContextProvider>
                <Toaster />
                <Navbar />
                <div id="root-modal"></div>
                {children}
                <Footer />
              </CartContextProvider>
            </AuthProvider>
          </AuthModalProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
