import type { Metadata } from "next";
import { Dosis } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/store/AuthContext";

const dosis = Dosis({
  variable: "--font-dosis",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dosis.variable} antialiased`}>
        <AuthProvider>
          <div id="root-modal"></div>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
